name: ci
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test_lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - uses: bahmutov/npm-install@v1
            - name: If this step fails run 'yarn lint' and 'yarn format' then commit again.
              run: |
                  yarn lint:check
                  yarn format:check

    check_if_version_upgraded:
        name: Check if version upgrade
        # When someone forks the repo and opens a PR we want to enables the tests to be run (the previous jobs)
        # but obviously only us should be allowed to release.
        # In the following check we make sure that we own the branch this CI workflow is running on before continuing.
        # Without this check, trying to release would fail anyway because only us have the correct secret.NPM_TOKEN but
        # it's cleaner to stop the execution instead of letting the CI crash.
        if: |
            github.event_name == 'push' || 
            github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login
        runs-on: ubuntu-latest
        needs: test_lint
        outputs:
            from_version: ${{ steps.step1.outputs.from_version }}
            to_version: ${{ steps.step1.outputs.to_version }}
            is_upgraded_version: ${{ steps.step1.outputs.is_upgraded_version }}
            is_pre_release: ${{steps.step1.outputs.is_pre_release }}
        steps:
            - uses: garronej/ts-ci@v2.1.0
              id: step1
              with:
                  action_name: is_package_json_version_upgraded
                  branch: ${{ github.head_ref || github.ref }}

    publish_on_npm:
        runs-on: ubuntu-latest
        needs: check_if_version_upgraded
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
            - uses: actions/setup-node@v4
              with:
                  registry-url: https://registry.npmjs.org/
            - uses: bahmutov/npm-install@v1
            - run: yarn build
            - run: npx -y -p denoify@1.5.7 enable_short_npm_import_path
              env:
                  DRY_RUN: "0"
            - uses: garronej/ts-ci@v2.1.0
              with:
                  action_name: remove_dark_mode_specific_images_from_readme
            - name: Publishing on NPM
              run: |
                  if [ "$(npm show . version)" = "$VERSION" ]; then
                    echo "This version is already published"
                    exit 0
                  fi
                  if [ "$NODE_AUTH_TOKEN" = "" ]; then
                    echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
                    false
                  fi
                  EXTRA_ARGS=""
                  if [ "$IS_PRE_RELEASE" = "true" ]; then
                      EXTRA_ARGS="--tag next"
                  fi
                  npm publish $EXTRA_ARGS
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
                  VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
                  IS_PRE_RELEASE: ${{ needs.check_if_version_upgraded.outputs.is_pre_release }}
